name: time_series_generator
description: a grpc microservice that generates tones
publish_to: none

environment:
  sdk: '^3.0.0'

dependencies:
  async: ^2.2.0
  grpc: ^3.1.0
  protobuf: ^2.1.0
  logging: ^1.1.0
  event_bus: ^2.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  broadcast_bloc: ^0.1.0-dev.2

dev_dependencies:
  lints: ^2.0.0
